import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const offresData = [
  // EMPLOIS - Ziguinchor
  {
    titre: "Développeur Web Full Stack",
    description: "Nous recherchons un développeur web full stack pour rejoindre notre équipe dynamique à Ziguinchor. Vous serez responsable du développement et de la maintenance de nos applications web. Compétences requises : React, Node.js, PostgreSQL.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "INFORMATIQUE",
    niveauExperience: "JUNIOR",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Tech Casamance SARL",
    salaireMin: 350000,
    salaireMax: 500000,
    devise: "FCFA",
    tags: ["React", "Node.js", "PostgreSQL", "JavaScript"],
  },
  {
    titre: "Comptable Senior",
    description: "Cabinet comptable basé à Ziguinchor recherche un comptable senior avec minimum 5 ans d'expérience. Gestion de la comptabilité clients, établissement des bilans et déclarations fiscales.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "FINANCE",
    niveauExperience: "CONFIRME",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Cabinet Diatta & Associés",
    salaireMin: 400000,
    salaireMax: 600000,
    devise: "FCFA",
    tags: ["Comptabilité", "SAGE", "Fiscalité", "Excel"],
  },
  {
    titre: "Commercial Terrain - Agroalimentaire",
    description: "Entreprise leader dans l'agroalimentaire recherche des commerciaux terrain pour développer notre réseau de distribution en Casamance. Véhicule de fonction fourni.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "COMMERCE",
    niveauExperience: "JUNIOR",
    localisation: "Ziguinchor et région",
    entreprise: "Casamance Agro Distribution",
    salaireMin: 200000,
    salaireMax: 350000,
    devise: "FCFA",
    tags: ["Vente", "Commercial", "Agroalimentaire"],
  },
  {
    titre: "Infirmier(ère) Diplômé(e) d'État",
    description: "Clinique privée à Ziguinchor recrute un(e) infirmier(ère) diplômé(e) d'État. Poste en CDI avec possibilité de gardes. Expérience en soins généraux souhaitée.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "SANTE",
    niveauExperience: "JUNIOR",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Clinique Casamance Santé",
    salaireMin: 250000,
    salaireMax: 400000,
    devise: "FCFA",
    tags: ["Santé", "Soins", "Infirmier"],
  },
  {
    titre: "Responsable Marketing Digital",
    description: "Agence de communication digitale recherche un responsable marketing digital pour gérer les campagnes de nos clients. Expertise en SEO, réseaux sociaux et publicité en ligne requise.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "MARKETING",
    niveauExperience: "CONFIRME",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Digital Casamance Agency",
    salaireMin: 400000,
    salaireMax: 650000,
    devise: "FCFA",
    tags: ["Marketing Digital", "SEO", "Réseaux Sociaux"],
  },
  {
    titre: "Réceptionniste Bilingue - Hôtellerie",
    description: "Hôtel 4 étoiles au Cap Skirring recherche un(e) réceptionniste bilingue français/anglais. Accueil des clients internationaux, gestion des réservations.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "TOURISME",
    niveauExperience: "JUNIOR",
    localisation: "Cap Skirring, Casamance",
    entreprise: "Hôtel Les Palétuviers",
    salaireMin: 180000,
    salaireMax: 280000,
    devise: "FCFA",
    tags: ["Hôtellerie", "Tourisme", "Accueil", "Bilingue"],
  },
  {
    titre: "Chef Cuisinier - Restaurant Gastronomique",
    description: "Restaurant gastronomique au Cap Skirring recherche un chef cuisinier créatif. Cuisine fusion africaine et internationale. Gestion d'une équipe de 5 personnes.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "TOURISME",
    niveauExperience: "CONFIRME",
    localisation: "Cap Skirring, Casamance",
    entreprise: "Restaurant Le Fromager",
    salaireMin: 300000,
    salaireMax: 500000,
    devise: "FCFA",
    tags: ["Cuisine", "Gastronomie", "Chef"],
  },
  {
    titre: "Technicien Agricole",
    description: "ONG spécialisée dans le développement agricole recherche un technicien agricole pour accompagner les producteurs de la région de Sédhiou. Formation et suivi des exploitations.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDD",
    secteur: "AGRICULTURE",
    niveauExperience: "JUNIOR",
    localisation: "Sédhiou, Casamance",
    entreprise: "ONG Casamance Verte",
    salaireMin: 200000,
    salaireMax: 300000,
    devise: "FCFA",
    tags: ["Agriculture", "Développement", "Formation"],
  },
  {
    titre: "Électricien Bâtiment",
    description: "Entreprise de BTP recherche un électricien qualifié pour chantiers en Casamance. Installations électriques résidentielles et commerciales. Permis B souhaité.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "CONSTRUCTION",
    niveauExperience: "CONFIRME",
    localisation: "Ziguinchor et région",
    entreprise: "BTP Casamance",
    salaireMin: 180000,
    salaireMax: 300000,
    devise: "FCFA",
    tags: ["Électricité", "BTP", "Construction"],
  },
  {
    titre: "Enseignant(e) de Mathématiques",
    description: "Établissement scolaire privé à Kolda recherche un(e) enseignant(e) de mathématiques pour le secondaire. Licence en mathématiques minimum requise.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "EDUCATION",
    niveauExperience: "JUNIOR",
    localisation: "Kolda, Casamance",
    entreprise: "Collège Excellence Kolda",
    salaireMin: 150000,
    salaireMax: 250000,
    devise: "FCFA",
    tags: ["Enseignement", "Mathématiques", "Éducation"],
  },
  // FORMATIONS
  {
    titre: "Formation en Développement Web - 6 mois",
    description: "Formation intensive en développement web : HTML, CSS, JavaScript, React, Node.js. Certification à la clé. Places limitées. Possibilité de stage en entreprise.",
    typeOffre: "FORMATION",
    secteur: "INFORMATIQUE",
    niveauExperience: "DEBUTANT",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Centre de Formation Numérique Casamance",
    salaireMin: 150000,
    salaireMax: 150000,
    devise: "FCFA",
    tags: ["Formation", "Web", "Développement", "Certification"],
  },
  {
    titre: "Formation Gestion de Projet - PMP",
    description: "Préparation à la certification PMP (Project Management Professional). Formation de 3 mois en présentiel et en ligne. Formateurs certifiés.",
    typeOffre: "FORMATION",
    secteur: "ADMINISTRATION",
    niveauExperience: "CONFIRME",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Institut de Management Casamance",
    salaireMin: 250000,
    salaireMax: 250000,
    devise: "FCFA",
    tags: ["PMP", "Gestion de Projet", "Certification"],
  },
  {
    titre: "Formation en Comptabilité et Gestion",
    description: "Formation professionnelle en comptabilité et gestion d'entreprise. Durée 4 mois. Logiciels SAGE et Excel avancé inclus. Attestation de formation.",
    typeOffre: "FORMATION",
    secteur: "FINANCE",
    niveauExperience: "DEBUTANT",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Centre de Formation Professionnelle",
    salaireMin: 100000,
    salaireMax: 100000,
    devise: "FCFA",
    tags: ["Comptabilité", "Gestion", "SAGE", "Formation"],
  },
  {
    titre: "Formation en Agriculture Biologique",
    description: "Formation pratique en agriculture biologique et permaculture. 2 mois de formation avec stage pratique sur exploitation. Hébergement possible.",
    typeOffre: "FORMATION",
    secteur: "AGRICULTURE",
    niveauExperience: "DEBUTANT",
    localisation: "Oussouye, Casamance",
    entreprise: "Ferme École Bio Casamance",
    salaireMin: 50000,
    salaireMax: 50000,
    devise: "FCFA",
    tags: ["Agriculture Bio", "Permaculture", "Formation"],
  },
  {
    titre: "Formation Guide Touristique",
    description: "Devenez guide touristique professionnel en Casamance. Formation de 3 mois : histoire, patrimoine, langues, techniques de guidage. Stage garanti.",
    typeOffre: "FORMATION",
    secteur: "TOURISME",
    niveauExperience: "DEBUTANT",
    localisation: "Cap Skirring, Casamance",
    entreprise: "Office du Tourisme Casamance",
    salaireMin: 75000,
    salaireMax: 75000,
    devise: "FCFA",
    tags: ["Tourisme", "Guide", "Formation", "Patrimoine"],
  },
  // BOURSES
  {
    titre: "Bourse d'Excellence - Master en France",
    description: "Bourse complète pour étudiants sénégalais souhaitant poursuivre un Master en France. Couvre frais de scolarité, logement et allocation mensuelle. Domaines : Sciences, Ingénierie, Économie.",
    typeOffre: "BOURSE",
    secteur: "EDUCATION",
    niveauExperience: "CONFIRME",
    localisation: "France",
    entreprise: "Campus France Sénégal",
    salaireMin: 0,
    salaireMax: 0,
    devise: "EUR",
    tags: ["Bourse", "Master", "France", "Excellence"],
  },
  {
    titre: "Bourse de Recherche Doctorale - ANSTS",
    description: "L'Académie Nationale des Sciences et Techniques du Sénégal offre des bourses de recherche doctorale. Domaines prioritaires : Environnement, Santé, Agriculture, Numérique.",
    typeOffre: "BOURSE",
    secteur: "RECHERCHE",
    niveauExperience: "EXPERT",
    localisation: "Sénégal",
    entreprise: "ANSTS",
    salaireMin: 0,
    salaireMax: 0,
    devise: "FCFA",
    tags: ["Bourse", "Doctorat", "Recherche"],
  },
  {
    titre: "Bourse Entrepreneuriat Jeunes Casamance",
    description: "Programme de bourse et accompagnement pour jeunes entrepreneurs de Casamance. Financement de projets innovants jusqu'à 5 millions FCFA. Mentorat inclus.",
    typeOffre: "BOURSE",
    secteur: "COMMERCE",
    niveauExperience: "DEBUTANT",
    localisation: "Casamance, Sénégal",
    entreprise: "Fondation Casamance Entreprendre",
    salaireMin: 0,
    salaireMax: 5000000,
    devise: "FCFA",
    tags: ["Bourse", "Entrepreneuriat", "Jeunes", "Financement"],
  },
  {
    titre: "Bourse Formation Professionnelle - BIT",
    description: "Le Bureau International du Travail offre des bourses de formation professionnelle pour jeunes diplômés. Formations en gestion, informatique, métiers techniques.",
    typeOffre: "BOURSE",
    secteur: "EDUCATION",
    niveauExperience: "JUNIOR",
    localisation: "Dakar, Sénégal",
    entreprise: "BIT Sénégal",
    salaireMin: 0,
    salaireMax: 0,
    devise: "FCFA",
    tags: ["Bourse", "Formation", "BIT", "Professionnelle"],
  },
  {
    titre: "Bourse Mobilité Étudiante - CEDEAO",
    description: "Programme de mobilité étudiante au sein de la CEDEAO. Échanges universitaires d'un semestre dans les pays membres. Frais de voyage et allocation couverts.",
    typeOffre: "BOURSE",
    secteur: "EDUCATION",
    niveauExperience: "JUNIOR",
    localisation: "Afrique de l'Ouest",
    entreprise: "CEDEAO - Programme Éducation",
    salaireMin: 0,
    salaireMax: 0,
    devise: "FCFA",
    tags: ["Bourse", "Mobilité", "CEDEAO", "Échange"],
  },
  // Plus d'emplois variés
  {
    titre: "Chauffeur Poids Lourd",
    description: "Entreprise de transport recherche chauffeur poids lourd expérimenté. Permis C obligatoire. Trajets Ziguinchor-Dakar principalement. Bonne connaissance des routes.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "TRANSPORT",
    niveauExperience: "CONFIRME",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Trans Casamance Express",
    salaireMin: 200000,
    salaireMax: 350000,
    devise: "FCFA",
    tags: ["Transport", "Chauffeur", "Poids Lourd"],
  },
  {
    titre: "Assistant(e) Administratif(ve)",
    description: "ONG internationale recherche un(e) assistant(e) administratif(ve) pour son bureau de Ziguinchor. Gestion administrative, accueil, organisation des réunions. Anglais apprécié.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDD",
    secteur: "ADMINISTRATION",
    niveauExperience: "JUNIOR",
    localisation: "Ziguinchor, Casamance",
    entreprise: "ONG Solidarité Internationale",
    salaireMin: 180000,
    salaireMax: 280000,
    devise: "FCFA",
    tags: ["Administration", "Assistant", "ONG"],
  },
  {
    titre: "Menuisier Ébéniste",
    description: "Atelier de menuiserie artisanale recherche menuisier ébéniste qualifié. Fabrication de meubles sur mesure en bois local. Créativité et précision requises.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "ARTISANAT",
    niveauExperience: "CONFIRME",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Ébénisterie Casamançaise",
    salaireMin: 150000,
    salaireMax: 280000,
    devise: "FCFA",
    tags: ["Menuiserie", "Ébénisterie", "Artisanat", "Bois"],
  },
  {
    titre: "Gestionnaire de Stock",
    description: "Supermarché à Ziguinchor recherche un gestionnaire de stock rigoureux. Gestion des inventaires, commandes fournisseurs, optimisation des stocks. Maîtrise Excel requise.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "COMMERCE",
    niveauExperience: "JUNIOR",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Super Marché Casamance",
    salaireMin: 180000,
    salaireMax: 280000,
    devise: "FCFA",
    tags: ["Logistique", "Stock", "Gestion", "Commerce"],
  },
  {
    titre: "Technicien Maintenance Informatique",
    description: "Société de services informatiques recherche technicien maintenance. Dépannage matériel et logiciel, installation réseaux, support utilisateurs. Déplacements en entreprise.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "INFORMATIQUE",
    niveauExperience: "JUNIOR",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Info Services Casamance",
    salaireMin: 200000,
    salaireMax: 350000,
    devise: "FCFA",
    tags: ["Informatique", "Maintenance", "Support", "Réseau"],
  },
  {
    titre: "Stage - Community Manager",
    description: "Agence de communication offre un stage de 6 mois en community management. Gestion des réseaux sociaux, création de contenu, analyse des performances. Possibilité d'embauche.",
    typeOffre: "EMPLOI",
    typeEmploi: "STAGE",
    secteur: "COMMUNICATION",
    niveauExperience: "DEBUTANT",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Com' Casamance",
    salaireMin: 75000,
    salaireMax: 100000,
    devise: "FCFA",
    tags: ["Stage", "Community Manager", "Réseaux Sociaux"],
  },
  {
    titre: "Avocat Junior - Cabinet d'Affaires",
    description: "Cabinet d'avocats d'affaires recherche avocat junior pour renforcer son équipe. Droit des sociétés, droit commercial, contentieux. CAPA requis.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "JURIDIQUE",
    niveauExperience: "JUNIOR",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Cabinet Juridique Casamance",
    salaireMin: 350000,
    salaireMax: 550000,
    devise: "FCFA",
    tags: ["Droit", "Avocat", "Juridique", "Affaires"],
  },
  {
    titre: "Responsable RH",
    description: "Entreprise industrielle recherche responsable RH expérimenté. Gestion du personnel, recrutement, formation, paie. Minimum 3 ans d'expérience en RH.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "RESSOURCES_HUMAINES",
    niveauExperience: "CONFIRME",
    localisation: "Ziguinchor, Casamance",
    entreprise: "Industries Casamance SA",
    salaireMin: 450000,
    salaireMax: 700000,
    devise: "FCFA",
    tags: ["RH", "Ressources Humaines", "Recrutement", "Formation"],
  },
  {
    titre: "Pêcheur Professionnel",
    description: "Coopérative de pêche à Kafountine recrute pêcheurs professionnels expérimentés. Pêche artisanale durable. Équipement fourni. Rémunération attractive selon prises.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "AGRICULTURE",
    niveauExperience: "CONFIRME",
    localisation: "Kafountine, Casamance",
    entreprise: "Coopérative Pêcheurs Kafountine",
    salaireMin: 150000,
    salaireMax: 400000,
    devise: "FCFA",
    tags: ["Pêche", "Maritime", "Coopérative"],
  },
  {
    titre: "Technicien Énergie Solaire",
    description: "Entreprise spécialisée en énergies renouvelables recherche technicien installation panneaux solaires. Formation assurée. Déplacements fréquents en zone rurale.",
    typeOffre: "EMPLOI",
    typeEmploi: "CDI",
    secteur: "ENERGIE",
    niveauExperience: "JUNIOR",
    localisation: "Ziguinchor et région",
    entreprise: "Solar Casamance",
    salaireMin: 200000,
    salaireMax: 350000,
    devise: "FCFA",
    tags: ["Énergie Solaire", "Renouvelable", "Installation"],
  },
];

async function main() {
  console.log('🌱 Début du seeding des offres...');
  
  // Get first admin user or create one
  let admin = await prisma.user.findFirst({
    where: { role: 'ADMIN' }
  });
  
  if (!admin) {
    admin = await prisma.user.create({
      data: {
        email: 'admin@noken.sn',
        username: 'admin',
        role: 'ADMIN',
        firstName: 'Admin',
        lastName: 'Noken',
        isEmailVerified: true,
        isActive: true,
      }
    });
    console.log('✅ Admin créé');
  }

  let created = 0;
  
  for (const offre of offresData) {
    try {
      await prisma.offre.create({
        data: {
          titre: offre.titre,
          description: offre.description,
          typeOffre: offre.typeOffre as any,
          typeEmploi: offre.typeEmploi as any || null,
          secteur: offre.secteur as any,
          niveauExperience: offre.niveauExperience as any,
          localisation: offre.localisation,
          entreprise: offre.entreprise,
          salaireMin: offre.salaireMin,
          salaireMax: offre.salaireMax,
          devise: offre.devise,
          tags: offre.tags,
          auteurId: admin.id,
          dateLimite: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), // 90 days from now
        }
      });
      created++;
    } catch (error) {
      console.log(`⚠️ Offre "${offre.titre}" peut-être déjà existante`);
    }
  }
  
  console.log(`✅ ${created} offres créées avec succès!`);
}

main()
  .catch((e) => {
    console.error('❌ Erreur:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
